export default peaks = 
	[
      { name: 'Longs Peak', 
        elevation: "14,255", 
        rating: "Very difficult", 
        distance: "16 miles", 
        near: "Estes Park",
        picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Fall05-LongsPeakCU_JPG_RSZ_md.jpg/280px-Fall05-LongsPeakCU_JPG_RSZ_md.jpg", 
        directions: "Drive south from Estes Park 10 miles on Colorado 7, then 1 mile west to a 'T' junction",
        route: "The trailhead for Longs is next to the ranger station.  Follow a good, moderately steep trail 6 miles west to the boulder field at about 12,800 feet."
      },
      { name: 'Mount Evans', 
        elevation: "14,264", 
        rating: "Moderate", 
        distance: "9 miles", 
        near: "Georgetown",
        picture: "https://www.codot.gov/travel/scenic-byways/north-central/mount-evans/photo-tour/Mt%20Evans%20-%20Summit%20Lake.JPG/image_preview", 
        directions: "Take I-70 west to Idaho Springs.  Take exit 240 and follow the sings to Mount Evans Road.",
        route: "Start from Summit Lake by hiking northwest around the lake to the start of the established trail up the ridge to Mount Spaulding."
      },
      { name: 'Mount Bierstadt', 
        elevation: "14,060", 
        rating: "Moderate", 
        distance: "6 miles", 
        near: "Georgetown",
        picture: "https://photos.smugmug.com/14ers/Front-Range/Mount-Evans-Bierstadt-14ers/i-BnVhn7r/0/9ca8685f/L/100_0053-L.jpg", 
        directions: "From Georgetown, drive south 11 miles along South Clear Creek Roud to Guanella Pass at 11,699 feet.",
        route: "Hike 1 mile on the boardwalk over the dreaded willows."
      },
      { name: 'Pikes Peak', 
        elevation: "14,110", 
        rating: "Moderate but long", 
        distance: "26 miles", 
        near: "Manitou Springs",
        picture: "https://s3.amazonaws.com/gs-geo-images/1d555f19-3f27-44ae-b24c-84cccdddbbef_l.jpg", 
        directions: "To reach the Barr Trail, drive to Manitou Springs and locate the City Hall.  Proceed west on US-25 about 0.5 miles to Ruxton Ave.",
        route: "From the trailhead the route switchbacks and climbs steeply for 3.5 miles, then rises gradually for the next 2 miles."
      },
      { name: 'Kit Carson Peak', 
        elevation: "14,165", 
        rating: "Very difficult", 
        distance: "6 miles", 
        near: "Westcliffe",
        picture: "https://s3.amazonaws.com/gs-geo-images/1d555f19-3f27-44ae-b24c-84cccdddbbef_l.jpg", 
        directions: "Approaching from the north, go 14 miles on CO 17 and US 285, or approaching from the south, go north 17 miles from Hooper on CO 17.",
        route: "Take the trail around the north side of the lake and continue above the falls."
      },
      { name: 'Humboldt Peak', 
        elevation: "14,064", 
        rating: "Moderate", 
        distance: "4 miles", 
        near: "Westcliffe",
        picture: "https://s3.amazonaws.com/gs-geo-images/1d555f19-3f27-44ae-b24c-84cccdddbbef_l.jpg", 
        directions: "From Westcliffe, drive southeast about 4.5 miles on CO 69 toward Walsenburg.",
        route: "From lower South Colony Lake, hike northwest on the trail up South Colony Creek to the east side."
      },
      { name: 'Crestone Peak', 
        elevation: "14,294", 
        rating: "Very difficult", 
        distance: "6 miles", 
        near: "Westcliffe",
        picture: "https://s3.amazonaws.com/gs-geo-images/1d555f19-3f27-44ae-b24c-84cccdddbbef_l.jpg", 
        directions: "From Westcliffe drive southeast about 4.5 miles on CO 69 toward Walsenburg.",
        route: "Follow the trail west past lower South Colony Lake."
      },
      { name: 'Crestone Needle', 
        elevation: "14,197", 
        rating: "Very difficult", 
        distance: "3 miles", 
        near: "Westcliffe",
        picture: "https://s3.amazonaws.com/gs-geo-images/1d555f19-3f27-44ae-b24c-84cccdddbbef_l.jpg", 
        directions: "From Westcliffe drive southeast about 4.5 miles on CO 69 toward Walsenburg.",
        route: "Follow the trail west past lower South Colony Lake."
      }
    ]